name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test Code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # - name: Install sodium
      #   run: sudo apt-get update && sudo apt-get install libsodium23 libsodium-dev -y

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 22.x
          elixir-version: 1.10.x

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      # - name: Run credo
      #   run: mix credo --strict
    
      - name: Test code
        run: mix test --cover